repos:
-   repo: https://github.com/bmorcos/pre-commit-hooks-cpp
    rev: 9a5aa38207bf557961110d6a4f7e3a9d352911f9
    hooks:
    -   id: cpplint
        files: src/colloid.cpp|!(src/colloid.hpp)|src/motif.cpp|!(src/motif.hpp)|!(src/utils.hpp)|!(src/json.hpp)
