name: escherc
channels:
  - conda-forge
dependencies:
  - python==3.9
  - ipykernel==6.25.2
  - ipywidgets==8.1.0
  - matplotlib==3.7.2
  - numpy==1.25.2
  - pandas==2.1.0
  - pip==23.2.1
  - pip:
    - pymatgen
